"""Add assigned_emails column

Revision ID: 6d693db56223
Revises: a262c8ae0e6c
Create Date: 2026-03-07 22:13:33.749912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d693db56223'
down_revision = 'a262c8ae0e6c'
branch_labels = None
depends_on = None
def upgrade():
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('assigned_emails', sa.Text(), nullable=False, server_default='[]')
        )
        batch_op.drop_column('assigned_email')

    # Skip password change for now
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.alter_column('password',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)


def downgrade():
    # Skip password revert
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.alter_column('password',
    #            existing_type=sa.String(length=100),
    #            type_=sa.VARCHAR(length=255),
    #            existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('assigned_emails')


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('task', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('assigned_emails', sa.Text(), nullable=True))
#         batch_op.drop_column('assigned_email')
#
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.alter_column('password',
#                existing_type=sa.VARCHAR(length=255),
#                type_=sa.String(length=100),
#                existing_nullable=True)
#
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.alter_column('password',
#                existing_type=sa.String(length=100),
#                type_=sa.VARCHAR(length=255),
#                existing_nullable=True)
#
#
#     with op.batch_alter_table('task', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('assigned_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
#         batch_op.drop_column('assigned_emails')

    # ### end Alembic commands ###
