"""initial migration

Revision ID: a262c8ae0e6c
Revises: 
Create Date: 2026-03-07 01:07:51.840192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a262c8ae0e6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('task_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_time')
        batch_op.drop_column('assigned_email')

    # ### end Alembic commands ###
